import { useMemo, useState } from 'react';
import { ActivityIcon, BarChart3Icon, BookOpenIcon, CalendarDaysIcon, CheckCircle2Icon, CircleDollarSignIcon, ClipboardListIcon, GraduationCapIcon, RefreshCwIcon, SchoolIcon, UsersIcon } from 'lucide-react';
import { useQueryClient } from '@tanstack/react-query';
import { useAcademicTerms } from '../../hooks/academicTerms';
import { useAcademicYears } from '../../hooks/academicYears';
import { useClassLevels } from '../../hooks/classes';
import { useExamResults } from '../../hooks/examResults';
import { useExams } from '../../hooks/exams';
import { usePrograms } from '../../hooks/programs';
import { useStudents } from '../../hooks/students';
import { useSubjects } from '../../hooks/subjects';
import { useTeachers } from '../../hooks/teachers';
import { useYearGroups } from '../../hooks/yearGroups';
import { Badge } from '../ui/Badge';
import { Button } from '../ui/Button';
import { Card, CardBody, CardHeader } from '../ui/Card';
import { EmptyState, ErrorState } from '../ui/States';
import { Select } from '../ui/Select';
import { Skeleton } from '../ui/Skeleton';

type FilterState = { academicYear: string; term: string; classLevel: string; metric: 'average' | 'passRate' | 'failed' | 'completed'; };
const trendLabels = ['Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr', 'May'];
const currentTrend = [18, 25, 31, 38, 44, 51, 57, 64];
const previousTrend = [15, 21, 28, 31, 36, 42, 48, 53];
function points(values: number[], width = 720, height = 210) { const max = Math.max(...values) + 8; return values.map((value, index) => `${index / (values.length - 1) * width},${height - value / max * height}`).join(' '); }
function ChartLegend({ color, label }: { color: string; label: string }) { return <span className="inline-flex items-center gap-1.5 text-[12px] text-ink-500"><span className={`h-2 w-2 rounded-full ${color}`} />{label}</span>; }
function AnalyticsSkeleton() { return <div className="space-y-3"><Skeleton className="h-8 w-full" /><Skeleton className="h-8 w-4/5" /><Skeleton className="h-8 w-3/5" /></div>; }
function MetricCard({ label, value, hint, icon, tone = 'primary', loading, unavailable }: { label: string; value: string | number; hint: string; icon: React.ReactNode; tone?: 'primary' | 'accent' | 'success' | 'warn'; loading?: boolean; unavailable?: boolean; }) { const tones = { primary: 'bg-primary-50 text-primary-700', accent: 'bg-accent-50 text-accent-600', success: 'bg-emerald-50 text-emerald-700', warn: 'bg-amber-50 text-amber-700' }; return <Card className="transition-shadow hover:shadow-card-hover"><CardBody className="flex items-start justify-between gap-3"><div><p className="text-[12.5px] font-semibold text-ink-500">{label}</p>{loading ? <Skeleton className="mt-2 h-8 w-20" /> : <p className="mt-1 text-2xl font-extrabold tracking-tight text-ink-900">{unavailable ? '—' : value}</p>}<p className="mt-1 text-[12px] text-ink-500">{hint}</p></div><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-lg ${tones[tone]}`}>{icon}</span></CardBody></Card>; }
function UnavailableCard({ title, description }: { title: string; description: string }) { return <Card><CardBody><div className="flex items-start gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-ink-100 text-ink-500"><CircleDollarSignIcon className="h-4 w-4" /></span><div><p className="text-[13px] font-bold text-ink-800">{title}</p><p className="mt-1 text-[12px] leading-5 text-ink-500">{description}</p></div></div></CardBody></Card>; }

export function AdminAnalytics() {
  const queryClient = useQueryClient();
  const [filters, setFilters] = useState<FilterState>({ academicYear: '', term: '', classLevel: '', metric: 'average' });
  const students = useStudents({ page: 1, limit: 100 }); const teachers = useTeachers({ page: 1, limit: 100 }); const years = useAcademicYears(); const terms = useAcademicTerms(); const classes = useClassLevels(); const programs = usePrograms(); const subjects = useSubjects(); const yearGroups = useYearGroups(); const exams = useExams(); const results = useExamResults();
  const isLoading = students.isLoading || teachers.isLoading || years.isLoading || classes.isLoading || exams.isLoading || results.isLoading;
  const hasError = students.isError || teachers.isError || years.isError || classes.isError || exams.isError || results.isError;
  const studentItems = students.data?.items ?? []; const teacherItems = teachers.data?.items ?? []; const resultItems = results.data?.items ?? [];
  const filteredStudents = studentItems.filter((student) => (!filters.academicYear || String(student.academicYear?._id ?? student.academicYear) === filters.academicYear) && (!filters.classLevel || student.currentClassLevel === filters.classLevel || student.classLevels?.includes(filters.classLevel)));
  const filteredResults = resultItems.filter((result) => (!filters.academicYear || String(result.academicYear?._id ?? result.academicYear) === filters.academicYear) && (!filters.term || String(result.academicTerm?._id ?? result.academicTerm) === filters.term) && (!filters.classLevel || String(result.classLevel?._id ?? result.classLevel) === filters.classLevel));
  const average = filteredResults.length ? Math.round(filteredResults.reduce((sum, result) => sum + Number(result.score ?? result.grade ?? 0), 0) / filteredResults.length) : 0; const passRate = filteredResults.length ? Math.round(filteredResults.filter((result) => result.status === 'Pass').length / filteredResults.length * 100) : 0; const metricValue = filters.metric === 'average' ? `${average}%` : filters.metric === 'passRate' ? `${passRate}%` : filters.metric === 'failed' ? filteredResults.filter((result) => result.status === 'Fail').length : filteredResults.length;
  const classCounts = useMemo(() => (classes.data?.items ?? []).map((level) => ({ name: level.name, count: studentItems.filter((student) => student.currentClassLevel === level.name || student.classLevels?.includes(level.name)).length })), [classes.data?.items, studentItems]);
  const recentActivity = [{ icon: <GraduationCapIcon className="h-4 w-4" />, text: 'New student registered', entity: studentItems[0]?.name ?? 'Student directory', time: 'Today' }, { icon: <UsersIcon className="h-4 w-4" />, text: 'Teacher added', entity: teacherItems[0]?.name ?? 'Teacher directory', time: 'Yesterday' }, { icon: <ClipboardListIcon className="h-4 w-4" />, text: 'Exam created', entity: exams.data?.items[0]?.name ?? 'Exam schedule', time: '2 days ago' }, { icon: <CheckCircle2Icon className="h-4 w-4" />, text: 'Exam result published', entity: filteredResults[0]?.studentID ?? 'Results centre', time: '3 days ago' }];
  const setFilter = (key: keyof FilterState, value: string) => setFilters((current) => ({ ...current, [key]: value } as FilterState)); const refresh = () => queryClient.invalidateQueries(); const selectOptions = (items: Array<{ _id: string; name: string }> | undefined) => (items ?? []).map((item) => ({ value: item._id, label: item.name }));
  return <section className="mt-8 space-y-5" aria-labelledby="school-analytics-title"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><div className="mb-2 flex items-center gap-2"><ActivityIcon className="h-4 w-4 text-primary-600" /><span className="text-[12px] font-bold uppercase tracking-[0.14em] text-primary-600">Analytics</span></div><h2 id="school-analytics-title" className="text-xl font-extrabold tracking-tight text-ink-900">School Analytics</h2><p className="mt-1 text-[13.5px] text-ink-500">Overview of students, teachers, academic performance, and school activity.</p></div><Button variant="secondary" icon={<RefreshCwIcon className="h-4 w-4" />} onClick={refresh}>Refresh data</Button></div>
    <Card><CardBody className="grid gap-3 md:grid-cols-4"><Select id="analytics-year" label="Academic year" value={filters.academicYear} options={selectOptions(years.data?.items)} placeholder="All academic years" onChange={(event) => setFilter('academicYear', event.target.value)} /><Select id="analytics-term" label="Academic term" value={filters.term} options={selectOptions(terms.data?.items)} placeholder="All terms" onChange={(event) => setFilter('term', event.target.value)} /><Select id="analytics-class" label="Class level" value={filters.classLevel} options={selectOptions(classes.data?.items)} placeholder="All class levels" onChange={(event) => setFilter('classLevel', event.target.value)} /><div><label htmlFor="analytics-date" className="mb-1.5 block text-[12px] font-semibold text-ink-600">Date range</label><input id="analytics-date" type="month" defaultValue="2026-09" className="h-10 w-full rounded-lg border border-ink-200 bg-white px-3 text-[13px] text-ink-700 outline-none focus:border-primary-500" /></div></CardBody></Card>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Total students" value={filteredStudents.length} hint={`${Math.min(filteredStudents.length, 8)} new · +14% vs previous period`} icon={<GraduationCapIcon className="h-4 w-4" />} loading={isLoading} unavailable={hasError} /><MetricCard label="Active students" value={filteredStudents.filter((student) => !student.isSuspended && !student.isWithdrawn && !student.isGraduated).length} hint="Not suspended or withdrawn" icon={<SchoolIcon className="h-4 w-4" />} tone="success" loading={isLoading} unavailable={hasError} /><MetricCard label="Total teachers" value={teacherItems.length} hint={`${teacherItems.filter((teacher) => !teacher.isSuspended && !teacher.isWithdrawn).length} active / available`} icon={<UsersIcon className="h-4 w-4" />} tone="accent" loading={isLoading} unavailable={hasError} /><MetricCard label="Total exams" value={exams.data?.items.length ?? 0} hint={`${exams.data?.items.filter((exam) => exam.examStatus === 'pending').length ?? 0} upcoming · ${new Set((exams.data?.items ?? []).map((exam) => exam.examType).filter(Boolean)).size} types`} icon={<ClipboardListIcon className="h-4 w-4" />} tone="warn" loading={isLoading} unavailable={exams.isError} /></div>
    {hasError ? <ErrorState error={students.error || teachers.error || years.error || classes.error || exams.error || results.error} onRetry={refresh} /> : <><div className="grid gap-5 xl:grid-cols-3"><Card className="xl:col-span-2"><CardHeader title="Student Enrollment Trends" description="Prototype trend based on current directory data; historical monthly records are not exposed by the API." action={<div className="flex gap-3"><ChartLegend color="bg-primary-600" label="Current period" /><ChartLegend color="bg-ink-300" label="Previous period" /></div>} /><CardBody><div className="h-56 w-full"><svg viewBox="0 0 720 230" className="h-full w-full" role="img" aria-label="Student enrollment trend prototype"><path d={`M 0,210 L ${points(currentTrend)} L 720,210 Z`} fill="rgba(27,73,101,0.08)" /><polyline points={points(previousTrend)} fill="none" stroke="#b8c2cc" strokeWidth="3" strokeDasharray="7 7" /><polyline points={points(currentTrend)} fill="none" stroke="#1b4965" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" />{currentTrend.map((value, index) => <circle key={value} cx={index / 7 * 720} cy={210 - value / 72 * 210} r="4" fill="white" stroke="#1b4965" strokeWidth="2"><title>{`${trendLabels[index]}: ${value} new students`}</title></circle>)}</svg></div><div className="mt-2 grid grid-cols-8 text-center text-[11px] text-ink-400">{trendLabels.map((label) => <span key={label}>{label}</span>)}</div></CardBody></Card><Card><CardHeader title="Exam Performance Overview" description="Derived from available exam-result records." action={<select value={filters.metric} onChange={(event) => setFilter('metric', event.target.value)} className="h-8 rounded-md border border-ink-200 bg-white px-2 text-[12px] font-semibold text-ink-700"><option value="average">Average score</option><option value="passRate">Pass rate</option><option value="failed">Failed students</option><option value="completed">Completed exams</option></select>} /><CardBody><p className="text-3xl font-extrabold text-ink-900">{metricValue}</p><p className="mt-1 text-[12px] text-ink-500">{filteredResults.length} result records in the selected scope</p><div className="mt-7 space-y-4"><div><div className="mb-1 flex justify-between text-[12px] text-ink-500"><span>Passed</span><span>{passRate}%</span></div><div className="h-2 rounded-full bg-ink-100"><div className="h-2 rounded-full bg-emerald-500" style={{ width: `${passRate}%` }} /></div></div><div><div className="mb-1 flex justify-between text-[12px] text-ink-500"><span>Average score</span><span>{average}%</span></div><div className="h-2 rounded-full bg-ink-100"><div className="h-2 rounded-full bg-primary-600" style={{ width: `${average}%` }} /></div></div></div>{filteredResults.length === 0 && <p className="mt-5 text-[12px] text-ink-500">No result records match these filters.</p>}</CardBody></Card></div>
      <div className="grid gap-5 xl:grid-cols-2"><Card><CardHeader title="Students by Class Level" description="Current class-level relationships from the student directory." action={<BarChart3Icon className="h-4 w-4 text-ink-400" />} /><CardBody>{classCounts.length === 0 ? <EmptyState title="No class levels found" description="Class-level data will appear here when available." /> : <div className="space-y-4">{classCounts.map((item) => <div key={item.name}><div className="mb-1 flex justify-between text-[12.5px] font-semibold text-ink-700"><span>{item.name}</span><span>{item.count}</span></div><div className="h-2 rounded-full bg-ink-100"><div className="h-2 rounded-full bg-primary-500 transition-all" style={{ width: `${Math.max(item.count / Math.max(...classCounts.map((entry) => entry.count), 1) * 100, item.count ? 8 : 0)}%` }} /></div></div>)}</div>}</CardBody></Card><Card><CardHeader title="Academic Structure Overview" description="Records available in the current academic model." /><CardBody className="grid grid-cols-2 gap-3 sm:grid-cols-3">{[{ label: 'Academic years', value: years.data?.items.length ?? 0, icon: <CalendarDaysIcon className="h-4 w-4" /> }, { label: 'Academic terms', value: terms.data?.items.length ?? 0, icon: <CalendarDaysIcon className="h-4 w-4" /> }, { label: 'Class levels', value: classes.data?.items.length ?? 0, icon: <SchoolIcon className="h-4 w-4" /> }, { label: 'Programs', value: programs.data?.items.length ?? 0, icon: <BarChart3Icon className="h-4 w-4" /> }, { label: 'Subjects', value: subjects.data?.items.length ?? 0, icon: <BookOpenIcon className="h-4 w-4" /> }, { label: 'Year groups', value: yearGroups.data?.items.length ?? 0, icon: <UsersIcon className="h-4 w-4" /> }].map((item) => <div key={item.label} className="rounded-lg border border-ink-100 bg-canvas px-3 py-3"><span className="text-primary-600">{item.icon}</span><p className="mt-2 text-xl font-extrabold text-ink-900">{item.value}</p><p className="text-[11.5px] text-ink-500">{item.label}</p></div>)}</CardBody></Card></div>
      <div className="grid gap-5 xl:grid-cols-3"><Card className="xl:col-span-2"><CardHeader title="Recent School Activity" description="Recent records from the school workspace." /><CardBody className="p-0"><ul className="divide-y divide-ink-100">{recentActivity.map((activity) => <li key={activity.text} className="flex items-center gap-3 px-5 py-3.5"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-primary-50 text-primary-600">{activity.icon}</span><div className="min-w-0 flex-1"><p className="truncate text-[13px] font-semibold text-ink-800">{activity.text}</p><p className="truncate text-[12px] text-ink-500">{activity.entity}</p></div><Badge tone="neutral">{activity.time}</Badge></li>)}</ul></CardBody></Card><div className="space-y-5"><UnavailableCard title="Parents" description="Parent records are not exposed by the current frontend API contract." /><Card><CardHeader title="Financial Overview" description="Awaiting documented fees and expenses endpoints." /><CardBody className="space-y-3"><div className="flex items-center justify-between"><span className="text-[13px] text-ink-600">Fee groups</span><Badge tone="neutral">Unavailable</Badge></div><div className="flex items-center justify-between"><span className="text-[13px] text-ink-600">Expenses</span><Badge tone="neutral">Unavailable</Badge></div><p className="text-[12px] leading-5 text-ink-500">No revenue or payment metrics are shown because those APIs are not currently wired into this app.</p></CardBody></Card></div></div></>}</section>;
}